name: Build and Push to ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-west-2.amazonaws.com
  IMAGE_NAME: cell-segmentation-job

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check if AWS_ACCOUNT_ID is defined
      run: |
        if [ -z "${{ secrets.AWS_ACCOUNT_ID }}" ]; then
          echo "Error: AWS_ACCOUNT_ID is not defined in GitHub Actions secrets."
          echo "Please set the AWS_ACCOUNT_ID secret in your repository settings."
          exit 0
        fi

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
  
    - name: Build, tag, and push image to Amazon ECR
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker buildx build \
          --push \
          --platform linux/amd64 \
          -t ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
          -f docker/Dockerfile \
          .